export const games = [
	{
		id: 1,
		date: '4/17/2022',
		away: 'Ravens',
		home: 'Raiders',
		score: '10 - 2',
		forecast: 'Sunny',
		map: '/map.jpg',
	},
	{
		id: 2,
		date: '4/17/2022',
		away: 'Ravens',
		home: 'Raiders',
		score: '10 - 2',
		forecast: 'Sunny',
		map: '/map.jpg',
	},
	{
		id: 3,
		date: '4/17/2022',
		away: 'Ravens',
		home: 'Raiders',
		score: '10 - 2',
		forecast: 'Sunny',
		map: '/map.jpg',
	},
	{
		id: 4,
		date: '4/17/2022',
		away: 'Ravens',
		home: 'Raiders',
		score: '10 - 2',
		forecast: 'Sunny',
		map: '/map.jpg',
	},
	{
		id: 5,
		date: '4/17/2022',
		away: 'Ravens',
		home: 'Raiders',
		score: '10 - 2',
		forecast: 'Sunny',
		map: '/map.jpg',
	},
	{
		id: 6,
		date: '4/17/2022',
		away: 'Ravens',
		home: 'Raiders',
		score: '10 - 2',
		forecast: 'Sunny',
		map: '/map.jpg',
	},
];
